### PR TITLE
Ask password to user when not provided

### PR DESCRIPTION
**Pull request by alefranz**
Currently the password need to be provided in clear or set in clear as environment variable.

This adds `getpass` to ask the password to the user without outputting it.
This happen only if the password is not set and is not running in CI mode.

Also includes the Contributor Agreement.

### CODE REVIEW

**Comment by duncanhall** [comment]
Thanks, this looks like a sensible solution. Could you add a test in [here](https://github.com/trainline/envmgr-cli/blob/master/tests/test_cli.py) to check that `getpass` is called as expected.

**Comment by duncanhall** [comment]
@alefranz Let me know if you need help adding tests?

**Comment by alefranz** [comment]
Hi @duncanhall, sorry for the delay.
I've added a test to verify `getpass` is called when required (that is not called in the other case seems unnecessary to test as if that was the case all tests would be failing as it is not mocked out).
I haven't seen any test around environment variables. Please let me know if I had missed something.

**Comment by duncanhall** [comment]
@alefranz There's an issue here with running the tests on a machine that *does* have the password set as an environment variable (eg, my local machine). In this case, `getpass` is never called and the test fails.

If you can add permissions for me to commit to your fork I'll submit an update to fix this.

**Comment by duncanhall** [comment]
Will get this released later today. Thanks for this, It's a good alternative to having passwords in plain text, I'm sure many will find it useful.

**Comment by duncanhall** [comment]
Released in https://github.com/trainline/envmgr-cli/releases/tag/1.9.0

**Comment by alefranz** [comment]
@duncanhall Thanks for taking the time of fixing the tests and merging this PR.

**Pull request merged**
